In [12]:
import scipy
from scipy.io import loadmat
import numpy as np
import matplotlib.pyplot as plt
import glob
import os
from spectral_connectivity import Multitaper
from spectral_connectivity import Connectivity
from spectral_connectivity import multitaper_connectivity
from pathlib import Path
from scipy import signal

In [13]:
pathsHPC = [path for path in Path('C:/Users/LENOVO/Desktop/sem7/internship/HomeCageHC').resolve().glob("**/*HPC*.mat")] # works (all full paths to HPC files)
pathsPFC = [path for path in Path('C:/Users/LENOVO/Desktop/sem7/internship/HomeCageHC').resolve().glob("**/*PFC*.mat")] # works (all full paths to PFC files)

frequency_of_interest = list(range(10,30))
sampling_frequency = 1000
n_trials = 40
n_signals = 2
no_of_files = len(pathsHPC)

In [14]:
for i in range(1): 
    dataHPC = scipy.io.loadmat(pathsHPC[i])
    dataPFC = scipy.io.loadmat(pathsPFC[i])
   
    
    current_dataHPC = dataHPC['HPC']
    current_dataPFC = dataPFC['PFC']

    n_time_samples = len(current_dataHPC)
    time = np.arange(0, n_time_samples)/sampling_frequency 
    signal = np.zeros((n_time_samples, n_signals))
    signal[:, 0] = np.reshape(current_dataHPC, (n_time_samples,))
    signal[:, 1] = np.reshape(current_dataPFC, (n_time_samples,))
    
    m = Multitaper(signal,
                   sampling_frequency=sampling_frequency,
                   time_halfbandwidth_product=5,
                   start_time=time[0])
    c = Connectivity(fourier_coefficients=m.fft(),
                     frequencies=m.frequencies)
    
    partial_directed_coherence = c.partial_directed_coherence()
    print(partial_directed_coherence)
    correlation = signal.correlate(current_dataHPC-np.mean(current_dataHPC), current_dataPFC - np.mean(current_dataPFC), mode="full")
    #lags = signal.correlation_lags(len(current_dataHPC), len(current_dataPFC), mode="full")
    #lag = lags[np.argmax(abs(correlation))]
    plt.plot(abs(correlation))
    plt.show()
  

[[[[9.38280245e-01 1.76630354e-04]
   [6.17197548e-02 9.99823370e-01]]

  [[7.79739783e-01 3.87858742e-02]
   [2.20260217e-01 9.61214126e-01]]

  [[6.53078086e-01 6.35810765e-02]
   [3.46921914e-01 9.36418923e-01]]

  ...

  [[8.95990243e-01 1.42118275e-02]
   [1.04009757e-01 9.85788173e-01]]

  [[9.93131906e-01 2.79734251e-03]
   [6.86809359e-03 9.97202657e-01]]

  [[9.93674868e-01 1.97158266e-03]
   [6.32513230e-03 9.98028417e-01]]]]


AttributeError: 'numpy.ndarray' object has no attribute 'correlate'